const number1 = 1;
const number2 = 2;
const product = number1 * number2;
console.log('value of product-', product);
console.log('data type of product-', typeof product);
const charge = 4;
const payment = 3;
const amountRemaining = charge - payment;
console.log('value of amountRemaining-', amountRemaining);
console.log('data type for amountRemaining-', typeof amountRemaining);
const test = 1;
const assignments = 2;
const final = 3;
const grade = (test + assignments + final) / 3;
console.log('value of grade-', grade);
console.log('data type of grade-', typeof grade);
const firstName = 'Bryant';
const lastName = 'Mendoza';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName-', fullName);
const ph = 5;
const isAcidic = ph < 7;
console.log('value os isAcidic-', isAcidic);
console.log('data type of isAcidic-', typeof isAcidic);
const numberOfSoilders = 100;
const isSparta = numberOfSoilders === 300;
console.log('value of isSparta-', isSparta);
console.log('data type of isSparta-', typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log('value of nickname-', nickname);
console.log('data type of nickname-', typeof nickname);
